package:
  name: protobuf
  version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('alpha-','a') }}.post{{ environ.get('GIT_DESCRIBE_NUMBER','') }}


source:
  git_url: https://github.com/google/protobuf.git
  git_rev: master

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - setuptools
    - six

test:
  # Python imports
  imports:
    - google.protobuf

about:
  home: http://code.google.com/p/protobuf/
  license: New BSD License
  summary: 'Protocol Buffers'
