package:
  name: xraylib
  version: master

source:
  git_url: https://github.com/tschoonj/xraylib

requirements:
  build:
    - python
    - setuptools
    - numpy #>=1.4.0
    - scipy >=0.7.0
    - cython

  run:
    - python
    - numpy #>=1.4.0
    - scipy >=0.7.0

about:
  license: BSD
  home: https://github.com/tschoonj/xraylib/wiki
  summary: A library for X-ray matter interaction cross sections for X-ray fluorescence applications
