package:
  name: xraylib
  version: master

source:
#  git_url: https://github.com/tschoonj/xraylib
   git_url: https://github.com/tacaswell/xraylib.git
   git_branch: py3k_fix
requirements:
  build:
    - python
    - setuptools
    - numpy #>=1.4.0
    - scipy >=0.7.0
    - cython
    - swig

  run:
    - python
    - numpy #>=1.4.0
    - scipy >=0.7.0


about:
  license: BSD
  home: https://github.com/tschoonj/xraylib/wiki
  summary: A library for X-ray matter interaction cross sections for X-ray fluorescence applications
