package:
  name: xraylib
  version: master

source:
  git_url: https://github.com/tschoonj/xraylib

requirements:
  build:
    - python
    - setuptools
    - numpy #>=1.4.0
    - scipy >=0.7.0

  run:
    - python
    - numpy #>=1.4.0
    - scipy >=0.7.0

about:
  license: LGPL
  home: https://github.com/ContinuumIO/hexrd
  summary: High energy diffraction microscopy
