package:
  name: pyepics
  version: !!str 3.2.3

source:
  fn: pyepics-3.2.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pyepics/pyepics-3.2.3.tar.gz
  md5: 0656d37f2e9cc3023b172e3e819811c0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyepics = pyepics:main
    #
    # Would create an entry point called pyepics that calls pyepics.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyparsing

  run:
    - python
    - pyparsing
    - numpy

test:
  # Python imports
  imports:
    - epics
    - epics.autosave
    - epics.compat
    - epics.devices

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pyepics.github.com/pyepics/
  license: Epics Open License
  summary: 'Epics Channel Access for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
